-- MySQL Script generated by MySQL Workbench
-- Fri Mar  8 19:40:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bronzedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bronzedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bronzedb` DEFAULT CHARACTER SET utf8 ;
USE `bronzedb` ;

-- -----------------------------------------------------
-- Table `bronzedb`.`customers_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bronzedb`.`customers_data` (
  `customer_id` VARCHAR(100) NOT NULL,
  `customer_unique_id` VARCHAR(100) NULL,
  `customer_zip_code_prefix` INT NULL,
  `customer_city` VARCHAR(45) NULL,
  `customer_state` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bronzedb`.`tb_geolocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bronzedb`.`tb_geolocation` (
  `geolocation_zip_code` INT NOT NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`geolocation_zip_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bronzedb`.`tb_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bronzedb`.`tb_orders` (
  `order_id` VARCHAR(100) NOT NULL,
  `customer_id` VARCHAR(100) NULL,
  `order_status` VARCHAR(45) NULL,
  `order_purchase_timestamp` DATETIME NULL,
  `order_approved_at` DATETIME NULL,
  `order_delivered_carrier_date` DATETIME NULL,
  `order_delivered_customer_date` DATETIME NULL,
  `order_estimated_delivery_date` DATETIME NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bronzedb`.`tb_order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bronzedb`.`tb_order_items` (
  `order_id` VARCHAR(100) NOT NULL,
  `order_item_id` VARCHAR(100) NULL,
  `product_id` VARCHAR(100) NULL,
  `seller_id` VARCHAR(100) NULL,
  `shipping_limit_date` DATETIME NULL,
  `price` DECIMAL(2) NULL,
  `freight_value` DECIMAL(2) NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bronzedb`.`tb_order_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bronzedb`.`tb_order_payments` (
  `order_id` VARCHAR(100) NOT NULL,
  `payment_sequential` VARCHAR(100) NULL,
  `payment_type` VARCHAR(100) NULL,
  `payment_installments` VARCHAR(45) NULL,
  `payment_value` DECIMAL(2) NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bronzedb`.`tb_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bronzedb`.`tb_products` (
  `product_id` VARCHAR(100) NOT NULL,
  `product_category_name` VARCHAR(45) NULL,
  `product_name_lenght` INT NULL,
  `product_description_lenght` INT NULL,
  `product_photos_qty` INT NULL,
  `product_weight_g` INT NULL,
  `product_length_cm` INT NULL,
  `product_height_cm` INT NULL,
  `product_width_cm` INT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bronzedb`.`tb_sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bronzedb`.`tb_sellers` (
  `seller_id` VARCHAR(100) NOT NULL,
  `seller_zip_code_prefix` INT NULL,
  `seller_city` VARCHAR(45) NULL,
  `seller_state` VARCHAR(45) NULL,
  PRIMARY KEY (`seller_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
